/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package io.github.dengue360.uiapp.ui;

import io.github.dengue360.etl.Trigger;
import io.github.dengue360.etl.exceptions.TransformException;
import io.github.dengue360.uiapp.HistoryDBFUpdate;
import java.io.IOException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Rafael
 */
public class App extends javax.swing.JFrame {
    private String file;
    /**
     * Creates new form Main
     * @throws java.lang.InterruptedException
     */
    public App() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        b1.setEnabled(false);
        //indeterminate();
    }
    
    private void indeterminate(){		
		SwingWorker<Void,Void> worker = new SwingWorker<Void,Void>(){

			@Override
			protected Void doInBackground() {
				jProgressBar1.setIndeterminate(true);
				b1.setEnabled(false);
                                select.setEnabled(false);
                                proc.setText("Processando... Aguarde!");
                                Trigger t = new Trigger(file);
                                try{
                                    Boolean result = false;
                                    while (!result) {                               
                                    //Todo o processo com o trigger vem aqui
                                        result = t.execute();  
                                    }
                                }catch(TransformException e){
                                    JOptionPane.showMessageDialog(null, "Erro no processo de transformação! "
                        + "\nPor favor, verifique sua conexão com a internet e repita a operação!", "Erro de Transformação", JOptionPane.INFORMATION_MESSAGE);
                                }catch (IOException ex) {
                                        JOptionPane.showMessageDialog(null, "Erro na leitura do dbf! "
                        + "\nPor favor, repita a operação!", "Erro de Leitura", JOptionPane.ERROR_MESSAGE);
                                }catch (Exception eex) {
                                        JOptionPane.showMessageDialog(null, "Erro ao salvar os dados! "
                        + "\nPor favor, repita a operação!", "Erro", JOptionPane.ERROR_MESSAGE);
                                }
			// para terminar 
                                
                                nameFile.setText("Arquivo Selecionado");
                                return null; 
			}

			@Override
			protected void done() {
				jProgressBar1.setIndeterminate(false);
                                select.setEnabled(true);
                                proc.setText("");
                                JOptionPane.showMessageDialog(null, "Processo Finalizado!!!", "",JOptionPane.INFORMATION_MESSAGE);
			}};
			worker.execute();
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        b1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        nameFile = new javax.swing.JLabel();
        proc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DENGUE 360 - AdminTool");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Panel1.setBackground(new java.awt.Color(164, 171, 238));

        jProgressBar1.setForeground(new java.awt.Color(38, 176, 38));

        b1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b1.setText("Processar Arquivo");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        select.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select.setText("Selecione um arquivo DBF do SINAN");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        nameFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameFile.setText("Arquivo Selecionado");

        proc.setText(" ");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(100, 100, 100))
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(select))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(nameFile))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1)
                            .addComponent(proc))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(select)
                .addGap(18, 18, 18)
                .addComponent(nameFile)
                .addGap(29, 29, 29)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(proc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(new FileNameExtensionFilter("DBF files", "dbf"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        int result = chooser.showOpenDialog(Panel1);
        if(result== chooser.APPROVE_OPTION){
            file = chooser.getSelectedFile().getPath();
            String dbfName = chooser.getSelectedFile().getName();
            try{
                HistoryDBFUpdate history = HistoryDBFUpdate.getInstance();
                if (!history.check(dbfName)) {
                    JOptionPane.showMessageDialog(null, "O arquivo selecionado já foi processado pelo sistema."
                            + "\n Por favor, repita a operação com outro arquivo!", "Arquivo já processado", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                history.save();
            } catch(IOException ioe){
                JOptionPane.showMessageDialog(null, "Erro na manipulação do arquivo de histórico!"
                        + "\n Repita a operação ou consulte a assistência técnica!", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
            }    
            nameFile.setText(dbfName);
            b1.setEnabled(true);
        }
    }//GEN-LAST:event_selectActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        indeterminate();
    }//GEN-LAST:event_b1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        int caixa = JOptionPane.showConfirmDialog(this, "Você deseja realmente sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (caixa == JOptionPane.YES_OPTION) {
                dispose();
        }
    }//GEN-LAST:event_formWindowClosing

//    /**
//     * @param args the command line arguments
//     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton b1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameFile;
    private javax.swing.JLabel proc;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables
}
